<a href="https://colab.research.google.com/github/kartikay-sharma06/Kartikay_Sharma/blob/main/Categorical%20ML%20Algorithm%20Comparision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(107)

In [ ]:
df.shape

(891, 15)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(784, 15)

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df['age'].fillna(df['age'].mean(),inplace=True)

In [ ]:
df.isna().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           582
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.drop(['who','embark_town','alive','class','adult_male','deck'],axis=1,inplace=True)

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'alone'],
      dtype='object')

In [ ]:
df.shape

(784, 9)

In [ ]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [ ]:
df.tail()

     survived  pclass     sex        age  sibsp  parch    fare embarked  alone
885         0       3  female  39.000000      0      5  29.125        Q  False
887         1       1  female  19.000000      0      0  30.000        S   True
888         0       3  female  29.869351      1      2  23.450        S  False
889         1       1    male  26.000000      0      0  30.000        C   True
890         0       3    male  32.000000      0      0   7.750        Q   True

In [ ]:
#to drop rows
df.dropna(subset=['embarked'],inplace=True)

In [ ]:
df.isna().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
alone       0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 782 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  782 non-null    int64
 1   pclass    782 non-null    int64
 2   sex       782 non-null    object
 3   age       782 non-null    float64
 4   sibsp     782 non-null    int64
 5   parch     782 non-null    int64
 6   fare      782 non-null    float64
 7   embarked  782 non-null    object
 8   alone     782 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 55.7+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sex']=le.fit_transform(df['sex'])
df['embarked']=le.fit_transform(df['embarked'])

In [ ]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [ ]:
df.astype(int)

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
885         0       3    0   39      0      5    29         1      0
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[782 rows x 9 columns]

In [ ]:
x=df.drop('survived',axis=1)
y=df['survived']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred=lr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
(accuracy_score(y_test,y_pred))

0.7579617834394905

In [ ]:
(confusion_matrix(y_test,y_pred))

array([[70, 18],
       [20, 49]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.80      0.79        88
           1       0.73      0.71      0.72        69

    accuracy                           0.76       157
   macro avg       0.75      0.75      0.75       157
weighted avg       0.76      0.76      0.76       157

KNN

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_scale=sc.fit_transform(x_train)
x_test_scale=sc.transform(x_test)

In [ ]:
(x_train_scale)

array([[ 0.89204545,  0.76307174, -0.74626914, ..., -0.47233993,
         0.58089314,  0.86642962],
       [ 0.89204545, -1.31049277, -0.4548122 , ..., -0.34510274,
         0.58089314, -1.15416184],
       [ 0.89204545, -1.31049277, -0.09049102, ..., -0.35670677,
        -1.94034445, -1.15416184],
       ...,
       [-0.29166667,  0.76307174,  0.85674403, ..., -0.39983874,
         0.58089314,  0.86642962],
       [ 0.89204545, -1.31049277,  2.38689295, ..., -0.4653779 ,
         0.58089314,  0.86642962],
       [ 0.89204545, -1.31049277, -0.02714643, ..., -0.18569614,
        -0.67972565, -1.15416184]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train_scale,y_train)

KNeighborsClassifier()

In [ ]:
y_prediction_knn=knn.predict(x_test_scale)

In [ ]:
accuracy_score(y_test,y_prediction_knn)

0.7515923566878981

In [ ]:
confusion_matrix(y_test,y_prediction_knn)

array([[73, 15],
       [24, 45]])

In [ ]:
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           0       0.75      0.83      0.79        88
           1       0.75      0.65      0.70        69

    accuracy                           0.75       157
   macro avg       0.75      0.74      0.74       157
weighted avg       0.75      0.75      0.75       157

Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

In [ ]:
nb_pred=nb.predict(x_test)

In [ ]:
accuracy_score(y_test,nb_pred)

0.7452229299363057

In [ ]:
confusion_matrix(y_test,nb_pred)

array([[68, 20],
       [20, 49]])

In [ ]:
print(classification_report(y_test,nb_pred))

              precision    recall  f1-score   support

           0       0.77      0.77      0.77        88
           1       0.71      0.71      0.71        69

    accuracy                           0.75       157
   macro avg       0.74      0.74      0.74       157
weighted avg       0.75      0.75      0.75       157

Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=42)
dt.fit(x_train_scale,y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_predict_dt=dt.predict(x_test_scale)

In [ ]:
accuracy_score(y_test,y_predict_dt)

0.7388535031847133

In [ ]:
confusion_matrix(y_test,y_predict_dt)

array([[71, 17],
       [24, 45]])

In [ ]:
print(classification_report(y_test,y_predict_dt))

              precision    recall  f1-score   support

           0       0.75      0.81      0.78        88
           1       0.73      0.65      0.69        69

    accuracy                           0.74       157
   macro avg       0.74      0.73      0.73       157
weighted avg       0.74      0.74      0.74       157